/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodayRouteImport } from './routes/today'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SentencesRouteImport } from './routes/sentences'
import { Route as RecallRouteImport } from './routes/recall'
import { Route as MatchRouteImport } from './routes/match'
import { Route as FlashcardsRouteImport } from './routes/flashcards'
import { Route as DecksRouteImport } from './routes/decks'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as IndexRouteImport } from './routes/index'

const TodayRoute = TodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SentencesRoute = SentencesRouteImport.update({
  id: '/sentences',
  path: '/sentences',
  getParentRoute: () => rootRouteImport,
} as any)
const RecallRoute = RecallRouteImport.update({
  id: '/recall',
  path: '/recall',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsRoute = FlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const DecksRoute = DecksRouteImport.update({
  id: '/decks',
  path: '/decks',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/deck': typeof DeckRoute
  '/decks': typeof DecksRoute
  '/flashcards': typeof FlashcardsRoute
  '/match': typeof MatchRoute
  '/recall': typeof RecallRoute
  '/sentences': typeof SentencesRoute
  '/stats': typeof StatsRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deck': typeof DeckRoute
  '/decks': typeof DecksRoute
  '/flashcards': typeof FlashcardsRoute
  '/match': typeof MatchRoute
  '/recall': typeof RecallRoute
  '/sentences': typeof SentencesRoute
  '/stats': typeof StatsRoute
  '/today': typeof TodayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/deck': typeof DeckRoute
  '/decks': typeof DecksRoute
  '/flashcards': typeof FlashcardsRoute
  '/match': typeof MatchRoute
  '/recall': typeof RecallRoute
  '/sentences': typeof SentencesRoute
  '/stats': typeof StatsRoute
  '/today': typeof TodayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/deck'
    | '/decks'
    | '/flashcards'
    | '/match'
    | '/recall'
    | '/sentences'
    | '/stats'
    | '/today'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deck'
    | '/decks'
    | '/flashcards'
    | '/match'
    | '/recall'
    | '/sentences'
    | '/stats'
    | '/today'
  id:
    | '__root__'
    | '/'
    | '/deck'
    | '/decks'
    | '/flashcards'
    | '/match'
    | '/recall'
    | '/sentences'
    | '/stats'
    | '/today'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DeckRoute: typeof DeckRoute
  DecksRoute: typeof DecksRoute
  FlashcardsRoute: typeof FlashcardsRoute
  MatchRoute: typeof MatchRoute
  RecallRoute: typeof RecallRoute
  SentencesRoute: typeof SentencesRoute
  StatsRoute: typeof StatsRoute
  TodayRoute: typeof TodayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/today': {
      id: '/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof TodayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sentences': {
      id: '/sentences'
      path: '/sentences'
      fullPath: '/sentences'
      preLoaderRoute: typeof SentencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recall': {
      id: '/recall'
      path: '/recall'
      fullPath: '/recall'
      preLoaderRoute: typeof RecallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards': {
      id: '/flashcards'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof FlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decks': {
      id: '/decks'
      path: '/decks'
      fullPath: '/decks'
      preLoaderRoute: typeof DecksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DeckRoute: DeckRoute,
  DecksRoute: DecksRoute,
  FlashcardsRoute: FlashcardsRoute,
  MatchRoute: MatchRoute,
  RecallRoute: RecallRoute,
  SentencesRoute: SentencesRoute,
  StatsRoute: StatsRoute,
  TodayRoute: TodayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
